
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-notify_db}
      POSTGRES_USER: ${POSTGRES_USER:-notify_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-notify_pass}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -lc "python manage.py migrate && gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  worker:
    build: .
    command: bash -lc "celery -A project worker -l info"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - web

  beat:
    build: .
    command: bash -lc "celery -A project beat -l info"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

volumes:
  pgdata:
